- hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Copy app files
      copy:
        src: /home/ubuntu/app/
        dest: /home/ubuntu/app/

    - name: Build Docker image
      command: docker build -t myapp /home/ubuntu/app/

    - name: Stop and remove existing container
      command: docker rm -f myapp-container
      ignore_errors: yes

    - name: Run Docker container
      command: docker run -d -p 8080:5000 --name myapp-container myapp  # Map 5000 (container) to 8080 (host)