---
- name: Configure Web Server
  hosts: web
  become: true

  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Copy Index File
      copy:
        content: "Updated Index Page!"
        dest: /var/www/html/index.html
