# .github/workflows/deploy.yml
name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init -chdir=./terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve -chdir=./terraform

    - name: Install Ansible
      run: sudo apt-get install -y ansible

    - name: Copy Ansible inventory
      run: echo "$(terraform output -raw instance_ips)" > ansible/inventory

    - name: Run Ansible Playbook
      run: ansible-playbook -i ansible/inventory ansible/playbook.yml