name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: terraform

      - name: Fetch EC2 Instance IP
        run: |
          echo "$(terraform output -raw instance_ip)" > instances.txt
        working-directory: terraform

      - name: Set up Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible
          echo "[web]" > ansible/inventory
          echo "$(cat terraform/instances.txt) ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa" >> ansible/inventory

      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory ansible/playbook.yml
