# .github/workflows/deploy.yml
name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: |
        cd terraform
        terraform init

    - name: Terraform Apply
      run: |
        cd terraform
        terraform apply -auto-approve

    - name: Install Ansible
      run: sudo apt-get install -y ansible

    - name: Copy Ansible inventory
      run: |
        cd terraform
        echo "$(terraform output -raw instance_ips)" > ../ansible/inventory

    - name: Run Ansible Playbook
      run: |
        cd ansible
        ansible-playbook -i inventory playbook.yml
